spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      default_schema: public
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20

logging:
  level:
    com.financialledge: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG

